main:
  - name: About
    url: '#about'
    weight: 1
  - name: All Posts
    url: /All/
    weight: 5
  - name: Grow Journal
    url: /growjournal/
    weight: 2
  - name: Personal
    url: /personal/
    weight: 3
  - name: Professional
    url: /professional/
    weight: 4